#!/bin/bash

PETEK_PATH="$HOME/.petek"
PETEK_WIDTH=500
PETEK_HEIGHT=400

zenity --text-info --title Petek --editable --filename=$PETEK_PATH --width $PETEK_WIDTH \
       --height $PETEK_HEIGHT > ${PETEK_PATH}.tmp && mv -f ${PETEK_PATH}.tmp $PETEK_PATH &
wmctrl -a Petek -b add,above
